// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOKt9VKC_aAZhMXlhfAWSoL0XTFyX8HB0',
    appId: '1:381489513964:web:d2557d3840271ac794ecc9',
    messagingSenderId: '381489513964',
    projectId: 'buzzwire-55635',
    authDomain: 'buzzwire-55635.firebaseapp.com',
    storageBucket: 'buzzwire-55635.appspot.com',
    measurementId: 'G-NQD0VJ4XT2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsN-4-bJRGqbXRua1Aj3TWtMB1G0oz5fU',
    appId: '1:381489513964:android:404a01ea79ad0e6294ecc9',
    messagingSenderId: '381489513964',
    projectId: 'buzzwire-55635',
    storageBucket: 'buzzwire-55635.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwBqYB8oXtegovIgvP8CUw17ehZKFz6_Q',
    appId: '1:381489513964:ios:7f6e84bd0fcb0a4c94ecc9',
    messagingSenderId: '381489513964',
    projectId: 'buzzwire-55635',
    storageBucket: 'buzzwire-55635.appspot.com',
    iosClientId: '381489513964-77f7t5jg5s70qeeokulukukt6ne0fcgn.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsPrintApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwBqYB8oXtegovIgvP8CUw17ehZKFz6_Q',
    appId: '1:381489513964:ios:76f8fae67fd83c5094ecc9',
    messagingSenderId: '381489513964',
    projectId: 'buzzwire-55635',
    storageBucket: 'buzzwire-55635.appspot.com',
    iosClientId: '381489513964-a7u9hptrfra41flthteh2jkg93lv0sq9.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsPrintApp.RunnerTests',
  );
}
